version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      workflow-actions:
        patterns:
          - '*'

  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: tuesday
    open-pull-requests-limit: 20
    groups:
      openrewrite:
        patterns:
          - 'org.openrewrite*'
      junit:
        patterns:
          - 'org.junit*'
      hibernate:
        patterns:
          - 'org.hibernate.orm:*'
      persistence-api:
        patterns:
          - 'jakarta.persistence:*'
