name: GitHub Actions linter

on:
  pull_request:

permissions: {}

jobs:
  actionlint:
    uses: hibernate/.github/.github/workflows/actionlint.yml@main
    permissions:
      contents: read
      pull-requests: read
